### PR TITLE
Atropos

### PR DESCRIPTION
**Pull request by jdidion**
I updated the Atropos MultiQC module to work with the latest version of MultiQC. This involved reorganizing the code such that each sub-component can be configured independently. I also had to change to using add_section() for adding plots, rather than manually adding section dicts to the parent section list.

It looks like it generally works now, although there may be some things that Phil want's us to improve before he'll merge this component into MultiQC proper. I know he mentioned wanting to do something different with the split read1/read2 plots. But at least it's a start.

### CODE REVIEW

**Comment by tanaes** [comment]
Awesome!! Thanks, I will pull this down and see how it works on my system.

**Comment by tanaes** [comment]
This looks super awesome to me, and ran fine on the test data I put up in my MultiQC_TestData [fork](https://github.com/tanaes/MultiQC_TestData/tree/atropos/data/modules/atropos/v1.1.5).

**Comment by jdidion** [comment]
Great! So do you want to submit a PR to MultiQC proper?

**Comment by tanaes** [comment]
If you're ready, I will do!

**Comment by jdidion** [comment]
Great, thanks!

**Pull request merged**
